name: Bisect
on:
  workflow_dispatch:
    inputs:
      path:
        description: 'Path to the files'
        required: true
        type: string
permissions:
  id-token: write
  contents: read
jobs:
  Bisect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: Render ECS Task Definition
        id: render-task-def
        uses: kbuaaaaaa/amazon-ecs-render-task-definition@v1
        with:
          task-definition: bisecting_task_definition.json
          container-name: bisecting-container
          image: ${{ steps.login-ecr.outputs.registry }}/compfuzzci/evaluation:${{github.event.inputs.commit}}
          execution-role-arn: ${{ secrets.ECS_TASK_EXECUTION_ROLE_ARN }}
          task-role-arn: ${{ secrets.ECS_TASK_ROLE_ARN }}
          command: bisect ${{github.event.inputs.path}}
      - name: Register Amazon ECS task definition
        id: register-task-def
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
      - name: Deploy ECS Task
        run: |
          aws ecs run-task --cluster ${{ secrets.ECS_CLUSTER }} --task-definition ${{ steps.register-task-def.outputs.task-definition-arn }} --count 1